fix travis deployment failure
Need to install pyopenssl otherwise travis machine throws this error..
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Reference: https://stackoverflow.com/questions/43267157/python-attributeerror-module-object-has-no-attribute-ssl-st-init/48569233